/** 区域选项 */
export const areaOptions: {
    label: string;
    value: string;
    children: {
        value: string;
        label: string;
        children?: {
            value: string;
            label: string;
        }[];
    }[];
  }[] = [
    { label: 'area.afg', value: 'Afghanistan', children: [
      {value: '', label: 'badakhshan'},
      {value: '', label: 'takhar'},
      {value: '', label: 'gowzjan'},
      {value: '', label: 'balkh'},
      {value: '', label: 'kunduz'},
      {value: '', label: 'samangan'},
      {value: '', label: 'faryab'},
      {value: '', label: 'baghlan'},
      {value: '', label: 'konarha'},
      {value: '', label: 'badghis'},
      {value: '', label: 'kapisa'},
      {value: '', label: 'laghman'},
      {value: '', label: 'herat'},
      {value: '', label: 'bamian'},
      {value: '', label: 'parvan'},
      {value: '', label: 'ghor'},
      {value: '', label: 'kabul'},
      {value: '', label: 'nangarhar'},
      {value: '', label: 'vardak'},
      {value: '', label: 'lowgar'},
      {value: '', label: 'oruzgan'},
      {value: '', label: 'ghazni'},
      {value: '', label: 'paktia'},
      {value: '', label: 'farah'},
      {value: '', label: 'helmand'},
      {value: '', label: 'paktika'},
      {value: '', label: 'zabol'},
      {value: '', label: 'quandahar'},
      {value: '', label: 'nimruz'},
      {value: '', label: 'panjshir'},
      {value: '', label: 'nuristan'},
      {value: '', label: 'khost'},
    ]},
    { label: 'area.chn', value: 'CHINA', children: [
      {value: '', label: 'heilongjiangSheng', children: [
        {value: '', label: '牡丹江市'},
        {value: '', label: '齐齐哈尔市'},
        {value: '', label: '绥化市'},
        {value: '', label: '鸡西市'},
        {value: '', label: '黑河市'},
        {value: '', label: '哈尔滨市'},
        {value: '', label: '大庆市'},
        {value: '', label: '大兴安岭地区'},
        {value: '', label: '伊春市'},
        {value: '', label: '鹤岗市'},
        {value: '', label: '双鸭山市'},
        {value: '', label: '佳木斯市'},
        {value: '', label: '七台河市'},
      ]},
      {value: '', label: 'neimongolZizhiqu', children: [
        {value: '', label: '兴安盟'},
        {value: '', label: '呼和浩特市'},
        {value: '', label: '包头市'},
        {value: '', label: '锡林郭勒盟'},
        {value: '', label: '乌海市'},
        {value: '', label: '赤峰市'},
        {value: '', label: '通辽市'},
        {value: '', label: '鄂尔多斯市'},
        {value: '', label: '阿拉善盟'},
        {value: '', label: '呼伦贝尔市'},
        {value: '', label: '巴彦淖尔市'},
        {value: '', label: '乌兰察布市'},
      ]},
      {value: '', label: 'xinjianguygurZizhiqu', children: [
        {value: '', label: '阿克苏地区'},
        {value: '', label: '博尔塔拉蒙古自治州'},
        {value: '', label: '吐鲁番市'},
        {value: '', label: '巴音郭楞蒙古自治州'},
        {value: '', label: '哈密市'},
        {value: '', label: '胡杨河市'},
        {value: '', label: '白杨市'},
        {value: '', label: '新星市'},
        {value: '', label: '克拉玛依市'},
        {value: '', label: '昆玉市'},
        {value: '', label: '可克达拉市'},
        {value: '', label: '图木舒克市'},
        {value: '', label: '阿拉尔市'},
        {value: '', label: '石河子市'},
        {value: '', label: '双河市'},
        {value: '', label: '铁门关市'},
        {value: '', label: '北屯市'},
        {value: '', label: '五家渠市'},
        {value: '', label: '昌吉回族自治州'},
        {value: '', label: '乌鲁木齐市'},
        {value: '', label: '和田地区'},
        {value: '', label: '克孜勒苏柯尔克孜自治州'},
        {value: '', label: '塔城地区'},
        {value: '', label: '喀什地区'},
        {value: '', label: '阿勒泰地区'},
        {value: '', label: '伊犁哈萨克自治州'},
      ]},
      {value: '', label: 'jilinSheng', children: [
        {value: '', label: '长春市'},
        {value: '', label: '延边朝鲜族自治州'},
        {value: '', label: '辽源市'},
        {value: '', label: '通化市'},
        {value: '', label: '吉林市'},
        {value: '', label: '四平市'},
        {value: '', label: '白城市'},
        {value: '', label: '白山市'},
        {value: '', label: '松原市'},
      ]},
      {value: '', label: 'gansuSheng', children: [
        {value: '', label: '庆阳市'},
        {value: '', label: '太子山天然林保护区'},
        {value: '', label: '甘南藏族自治州'},
        {value: '', label: '中农发山丹马场'},
        {value: '', label: '莲花山风景林自然保护区'},
        {value: '', label: '平凉市'},
        {value: '', label: '酒泉市'},
        {value: '', label: '武威市'},
        {value: '', label: '临夏回族自治州'},
        {value: '', label: '张掖市'},
        {value: '', label: '白银市'},
        {value: '', label: '天水市'},
        {value: '', label: '嘉峪关市'},
        {value: '', label: '金昌市'},
        {value: '', label: '定西市'},
        {value: '', label: '兰州市'},
        {value: '', label: '陇南市'},
      ]},
      {value: '', label: 'beijingShi', children: [
        // {value: '', label: '东城区'},
        // {value: '', label: '西城区'},
        // {value: '', label: '朝阳区'},
        // {value: '', label: '海淀区'},
        // {value: '', label: '丰台区'},
        // {value: '', label: '石景山区'},
        // {value: '', label: '房山区'},
        // {value: '', label: '延庆区'},
        // {value: '', label: '门头沟区'},
        // {value: '', label: '通州区'},
        // {value: '', label: '顺义区'},
        // {value: '', label: '昌平区'},
        // {value: '', label: '大兴区'},
        // {value: '', label: '怀柔区'},
        // {value: '', label: '平谷区'},
      ]},
      {value: '', label: 'sHanxiSheng', children: [
        {value: '', label: '吕梁市'},
        {value: '', label: '太原市'},
        {value: '', label: '大同市'},
        {value: '', label: '阳泉市'},
        {value: '', label: '长治市'},
        {value: '', label: '晋城市'},
        {value: '', label: '朔州市'},
        {value: '', label: '晋中市'},
        {value: '', label: '运城市'},
        {value: '', label: '忻州市'},
        {value: '', label: '临汾市'},
      ]},
      {value: '', label: 'shanxiSheng', children: [
        {value: '', label: '西安市'},
        {value: '', label: '商洛市'},
        {value: '', label: '安康市'},
        {value: '', label: '榆林市'},
        {value: '', label: '汉中市'},
        {value: '', label: '延安市'},
        {value: '', label: '渭南市'},
        {value: '', label: '咸阳市'},
        {value: '', label: '宝鸡市'},
        {value: '', label: '铜川市'}]
      },
      {value: '', label: 'ningxiahuizuZizhiqu', children: [
        {value: '', label: '固原市'},
        {value: '', label: '中卫市'},
        {value: '', label: '石嘴山市'},
        {value: '', label: '吴忠市'},
        {value: '', label: '银川市'},
      ]},
      {value: '', label: 'qinghaiSheng', children: [
        {value: '', label: '玉树藏族自治州'},
        {value: '', label: '海西蒙古族藏族自治州'},
        {value: '', label: '海南藏族自治州'},
        {value: '', label: '海东市'},
        {value: '', label: '果洛藏族自治州'},
        {value: '', label: '黄南藏族自治州'},
        {value: '', label: '西宁市'},
        {value: '', label: '海北藏族自治州'},
      ]},
      {value: '', label: 'xizangZizhiqu', children: [
        {value: '', label: '那曲市'},
        {value: '', label: '山南市'},
        {value: '', label: '阿里地区'},
        {value: '', label: '日喀则市'},
        {value: '', label: '拉萨市'},
        {value: '', label: '林芝市'},
        {value: '', label: '昌都市'},
      ]},
      {value: '', label: 'anhuiSheng', children: [
        {value: '', label: '宣城市'},
        {value: '', label: '淮北市'},
        {value: '', label: '铜陵市'},
        {value: '', label: '亳州市'},
        {value: '', label: '淮南市'},
        {value: '', label: '池州市'},
        {value: '', label: '马鞍山市'},
        {value: '', label: '安庆市'},
        {value: '', label: '黄山市'},
        {value: '', label: '滁州市'},
        {value: '', label: '芜湖市'},
        {value: '', label: '六安市'},
        {value: '', label: '蚌埠市'},
        {value: '', label: '阜阳市'},
        {value: '', label: '宿州市'},
        {value: '', label: '合肥市'}]
      },
      {value: '', label: 'sichuanSheng', children: [
        {value: '', label: '广安市'},
        {value: '', label: '攀枝花市'},
        {value: '', label: '宜宾市'},
        {value: '', label: '自贡市'},
        {value: '', label: '雅安市'},
        {value: '', label: '德阳市'},
        {value: '', label: '达州市'},
        {value: '', label: '乐山市'},
        {value: '', label: '凉山彝族自治州'},
        {value: '', label: '眉山市'},
        {value: '', label: '南充市'},
        {value: '', label: '成都市'},
        {value: '', label: '甘孜藏族自治州'},
        {value: '', label: '内江市'},
        {value: '', label: '阿坝藏族羌族自治州'},
        {value: '', label: '资阳市'},
        {value: '', label: '广元市'},
        {value: '', label: '巴中市'},
        {value: '', label: '绵阳市'},
        {value: '', label: '遂宁市'},
      ]},
      {value: '', label: 'henanSheng', children: [
        {value: '', label: '濮阳市'},
        {value: '', label: '安阳市'},
        {value: '', label: '周口市'},
        {value: '', label: '鹤壁市'},
        {value: '', label: '驻马店市'},
        {value: '', label: '新乡市'},
        {value: '', label: '焦作市'},
        {value: '', label: '郑州市'},
        {value: '', label: '三门峡市'},
        {value: '', label: '开封市'},
        {value: '', label: '南阳市'},
        {value: '', label: '洛阳市'},
        {value: '', label: '济源市'},
        {value: '', label: '商丘市'},
        {value: '', label: '平顶山市'},
        {value: '', label: '信阳市'},
        {value: '', label: '许昌市'},
        {value: '', label: '漯河市'},
      ]},
      {value: '', label: 'hubeiSheng', children: [
        {value: '', label: '鄂州市'},
        {value: '', label: '荆门市'},
        {value: '', label: '孝感市'},
        {value: '', label: '十堰市'},
        {value: '', label: '天门市'},
        {value: '', label: '潜江市'},
        {value: '', label: '仙桃市'},
        {value: '', label: '恩施土家族苗族自治州'},
        {value: '', label: '宜昌市'},
        {value: '', label: '襄阳市'},
        {value: '', label: '荆州市'},
        {value: '', label: '黄冈市'},
        {value: '', label: '武汉市'},
        {value: '', label: '咸宁市'},
        {value: '', label: '黄石市'},
        {value: '', label: '随州市'},
        {value: '', label: '神农架林区'},
      ]},
      {value: '', label: 'chongqingShi', children: [
        // {value: '', label: '渝中区'},
        // {value: '', label: '大渡口区'},
        // {value: '', label: '江北区'},
        // {value: '', label: '沙坪坝区'},
        // {value: '', label: '九龙坡区'},
        // {value: '', label: '南岸区'},
        // {value: '', label: '北碚区'},
        // {value: '', label: '綦江区'},
        // {value: '', label: '大足区'},
        // {value: '', label: '渝北区'},
        // {value: '', label: '巴南区'},
        // {value: '', label: '黔江区'},
        // {value: '', label: '长寿区'},
        // {value: '', label: '江津区'},
        // {value: '', label: '合川区'},
        // {value: '', label: '永川区'},
        // {value: '', label: '南川区'},
      ]},
      {value: '', label: 'hunanSheng', children: [
        {value: '', label: '邵阳市'},
        {value: '', label: '岳阳市'},
        {value: '', label: '常德市'},
        {value: '', label: '张家界市'},
        {value: '', label: '怀化市'},
        {value: '', label: '长沙市'},
        {value: '', label: '娄底市'},
        {value: '', label: '株洲市'},
        {value: '', label: '湘潭市'},
        {value: '', label: '衡阳市'},
        {value: '', label: '湘西土家族苗族自治州'},
        {value: '', label: '郴州市'},
        {value: '', label: '永州市'},
        {value: '', label: '益阳市'},
      ]},
      {value: '', label: 'jiangxiSheng', children: [
        {value: '', label: '景德镇市'},
        {value: '', label: '萍乡市'},
        {value: '', label: '南昌市'},
        {value: '', label: '鹰潭市'},
        {value: '', label: '赣州市'},
        {value: '', label: '九江市'},
        {value: '', label: '新余市'},
        {value: '', label: '吉安市'},
        {value: '', label: '宜春市'},
        {value: '', label: '抚州市'},
        {value: '', label: '上饶市'}]
      },
      {value: '', label: 'yunnanSheng', children: [
        {value: '', label: '楚雄彝族自治州'},
        {value: '', label: '迪庆藏族自治州'},
        {value: '', label: '红河哈尼族彝族自治州'},
        {value: '', label: '昆明市'},
        {value: '', label: '德宏傣族景颇族自治州'},
        {value: '', label: '怒江傈僳族自治州'},
        {value: '', label: '普洱市'},
        {value: '', label: '丽江市'},
        {value: '', label: '临沧市'},
        {value: '', label: '玉溪市'},
        {value: '', label: '文山壮族苗族自治州'},
        {value: '', label: '曲靖市'},
        {value: '', label: '昭通市'},
        {value: '', label: '大理白族自治州'},
        {value: '', label: '西双版纳傣族自治州'},
        {value: '', label: '保山市'}]
      },
      {value: '', label: 'hongkongTebiexingzhengqu', children: [
        {value: '', label: '中西区'},
        {value: '', label: '湾仔区'},
        {value: '', label: '东区'},
        {value: '', label: '南区'},
        {value: '', label: '深水埗区'},
        {value: '', label: '油尖旺区'},
        {value: '', label: '九龙城区'},
        {value: '', label: '黄大仙区'},
        {value: '', label: '观塘区'},
        {value: '', label: '北区'},
        {value: '', label: '大埔区'},
        {value: '', label: '沙田区'},
        {value: '', label: '西贡区'},
        {value: '', label: '荃湾区'},
        {value: '', label: '屯门区'},
        {value: '', label: '元朗区'},
        {value: '', label: '葵青区'},
        {value: '', label: '离岛区'},
      ]},
      {value: '', label: 'aomenTebiexingzhengqu', children: [
        {value: '', label: '圣方济各堂区'},
        {value: '', label: '路凼填海区'},
        {value: '', label: '嘉模堂区'},
        {value: '', label: '大堂区'},
        {value: '', label: '风顺堂区'},
        {value: '', label: '花王堂区'},
        {value: '', label: '望德堂区'},
        {value: '', label: '花地玛堂区'},
      ]},
      {value: '', label: 'hebeiSheng', children: [
        {value: '', label: '石家庄市'},
        {value: '', label: '唐山市'},
        {value: '', label: '秦皇岛市'},
        {value: '', label: '邯郸市'},
        {value: '', label: '邢台市'},
        {value: '', label: '保定市'},
        {value: '', label: '张家口市'},
        {value: '', label: '承德市'},
        {value: '', label: '沧州市'},
        {value: '', label: '廊坊市'},
        {value: '', label: '衡水市'},
      ]},
      {value: '', label: 'liaoningSheng', children: [
        {value: '', label: '朝阳市'},
        {value: '', label: '大连市'},
        {value: '', label: '葫芦岛市'},
        {value: '', label: '鞍山市'},
        {value: '', label: '盘锦市'},
        {value: '', label: '铁岭市'},
        {value: '', label: '沈阳市'},
        {value: '', label: '丹东市'},
        {value: '', label: '锦州市'},
        {value: '', label: '抚顺市'},
        {value: '', label: '本溪市'},
        {value: '', label: '营口市'},
        {value: '', label: '阜新市'},
        {value: '', label: '辽阳市'},
      ]},
      {value: '', label: 'shandongSheng', children: [
        {value: '', label: '济南市'},
        {value: '', label: '临沂市'},
        {value: '', label: '威海市'},
        {value: '', label: '日照市'},
        {value: '', label: '枣庄市'},
        {value: '', label: '滨州市'},
        {value: '', label: '东营市'},
        {value: '', label: '菏泽市'},
        {value: '', label: '青岛市'},
        {value: '', label: '德州市'},
        {value: '', label: '淄博市'},
        {value: '', label: '聊城市'},
        {value: '', label: '济宁市'},
        {value: '', label: '泰安市'},
        {value: '', label: '烟台市'},
        {value: '', label: '潍坊市'},
      ]},
      {value: '', label: 'zhejiangSheng', children: [
        {value: '', label: '舟山市'},
        {value: '', label: '衢州市'},
        {value: '', label: '金华市'},
        {value: '', label: '绍兴市'},
        {value: '', label: '杭州市'},
        {value: '', label: '丽水市'},
        {value: '', label: '台州市'},
        {value: '', label: '湖州市'},
        {value: '', label: '嘉兴市'},
        {value: '', label: '温州市'},
        {value: '', label: '宁波市'},
      ]},
      {value: '', label: 'tianjinShi', children: [
        // {value: '', label: '河东区'},
        // {value: '', label: '河西区'},
        // {value: '', label: '南开区'},
        // {value: '', label: '和平区'},
        // {value: '', label: '红桥区'},
        // {value: '', label: '河北区'},
        // {value: '', label: '塘沽区'},
        // {value: '', label: '西青区'},
        // {value: '', label: '东丽区'},
        // {value: '', label: '津南区'},
        // {value: '', label: '北辰区'},
        // {value: '', label: '武清区'},
        // {value: '', label: '宝坻区'},
        // {value: '', label: '宁河区'},
        // {value: '', label: '静海区'},
        // {value: '', label: '蓟州区'},
      ]},
      {value: '', label: 'jiangsuSheng', children: [
        {value: '', label: '盐城市'},
        {value: '', label: '淮安市'},
        {value: '', label: '镇江市'},
        {value: '', label: '扬州市'},
        {value: '', label: '徐州市'},
        {value: '', label: '无锡市'},
        {value: '', label: '南京市'},
        {value: '', label: '宿迁市'},
        {value: '', label: '泰州市'},
        {value: '', label: '连云港市'},
        {value: '', label: '南通市'},
        {value: '', label: '苏州市'},
        {value: '', label: '常州市'},
      ]},
      {value: '', label: 'shanghaiShi', children: [
        // {value: '', label: '黄浦区'},
        // {value: '', label: '徐汇区'},
        // {value: '', label: '长宁区'},
        // {value: '', label: '静安区'},
        // {value: '', label: '普陀区'},
        // {value: '', label: '虹口区'},
        // {value: '', label: '杨浦区'},
        // {value: '', label: '闵行区'},
        // {value: '', label: '宝山区'},
        // {value: '', label: '嘉定区'},
        // {value: '', label: '浦东新区'},
        // {value: '', label: '金山区'},
        // {value: '', label: '松江区'},
        // {value: '', label: '青浦区'},
        // {value: '', label: '奉贤区'},
        // {value: '', label: '崇明区'},
      ]},
      {value: '', label: 'guizhouSheng', children: [
        {value: '', label: '六盘水市'},
        {value: '', label: '贵阳市'},
        {value: '', label: '安顺市'},
        {value: '', label: '黔南布依族苗族自治州'},
        {value: '', label: '遵义市'},
        {value: '', label: '黔东南苗族侗族自治州'},
        {value: '', label: '泸州市'},
        {value: '', label: '黔西南布依族苗族自治州'},
        {value: '', label: '铜仁市'},
        {value: '', label: '毕节市'}]
      },
      {value: '', label: 'guangxizhuangzuZizhiqu', children: [
        {value: '', label: '贺州市'},
        {value: '', label: '百色市'},
        {value: '', label: '梧州市'},
        {value: '', label: '桂林市'},
        {value: '', label: '崇左市'},
        {value: '', label: '柳州市'},
        {value: '', label: '来宾市'},
        {value: '', label: '南宁市'},
        {value: '', label: '河池市'},
        {value: '', label: '贵港市'},
        {value: '', label: '钦州市'},
        {value: '', label: '防城港市'},
        {value: '', label: '北海市'},
        {value: '', label: '玉林市'}]
      },
      {value: 'Taiwan', label: 'taiwanSheng', children: [
        // {value: 'Taipei', label: '台北市'},
        // {value: 'New Taipei', label: '新北市'},
        // {value: 'Taoyuan', label: '桃园市'},
        // {value: 'Taichung', label: '台中市'},
        // {value: 'Tainan', label: '台南市'},
        // {value: 'Kaohsiung', label: '高雄市'},
        // {value: 'Keelung', label: '基隆市'},
        // {value: 'Hsinchu City', label: '新竹市'},
        // {value: 'Chiayi City', label: '嘉义市'},
        // {value: 'Chiayi County', label: '嘉义县'},
        // {value: 'Pingtung', label: '屏东县'},
        // {value: 'Kinmen', label: '金门'},
        // {value: 'Taitung', label: '台东县'},
        // {value: 'Hualien', label: '花莲县'},
        // {value: 'Nantou', label: '南投县'},
        // {value: 'Yulin', label: '云林县'},
        // {value: 'Changhua', label: '彰化县'},
        // {value: 'Miaoli', label: '苗栗县'},
        // {value: 'Yilan', label: '宜兰县'},
        // {value: 'Hsinchu County', label: '新竹县'},
      ]},
      {value: '', label: 'fujianSheng', children: [
        {value: '', label: '三明市'},
        {value: '', label: '泉州市'},
        {value: '', label: '厦门市'},
        {value: '', label: '莆田市'},
        {value: '', label: '龙岩市'},
        {value: '', label: '宁德市'},
        {value: '', label: '漳州市'},
        {value: '', label: '南平市'},
        {value: '', label: '福州市'}]
      },
      {value: '', label: 'guangdongSheng', children: [
        {value: '', label: '汕尾市'},
        {value: '', label: '汕头市'},
        {value: '', label: '梅州市'},
        {value: '', label: '深圳市'},
        {value: '', label: '珠海市'},
        {value: '', label: '河源市'},
        {value: '', label: '阳江市'},
        {value: '', label: '佛山市'},
        {value: '', label: '肇庆市'},
        {value: '', label: '广州市'},
        {value: '', label: '惠州市'},
        {value: '', label: '韶关市'},
        {value: '', label: '揭阳市'},
        {value: '', label: '云浮市'},
        {value: '', label: '中山市'},
        {value: '', label: '清远市'},
        {value: '', label: '江门市'},
        {value: '', label: '东莞市'},
        {value: '', label: '湛江市'},
        {value: '', label: '茂名市'},
        {value: '', label: '潮州市'},
      ]},
      {value: '', label: 'hainanSheng', children: [
        {value: '', label: '三沙市'},
        {value: '', label: '三亚市'},
        {value: '', label: '保亭黎族苗族自治县'},
        {value: '', label: '陵水黎族自治县'},
        {value: '', label: '乐东黎族自治县'},
        {value: '', label: '昌江黎族自治县'},
        {value: '', label: '白沙黎族自治县'},
        {value: '', label: '临高县'},
        {value: '', label: '澄迈县'},
        {value: '', label: '屯昌县'},
        {value: '', label: '定安县'},
        {value: '', label: '海口市'},
        {value: '', label: '琼中黎族苗族自治县'},
        {value: '', label: '儋州市'},
        {value: '', label: '东方市'},
        {value: '', label: '万宁市'},
        {value: '', label: '文昌市'},
        {value: '', label: '琼海市'},
        {value: '', label: '五指山市'},
      ]},
    ]},
    { label: 'area.pak', value: 'Pakistan', children: [
      {value: '', label: 'federallyAdministeredTribalAreas'},
      {value: '', label: 'punjab'},
      {value: '', label: 'baluchistan'},
      {value: '', label: 'sindh'},
      {value: '', label: 'northWestFrontier'},
      {value: '', label: 'islamabadCapitalArea'},
      {value: '', label: 'northernAreas'},
      {value: '', label: 'azadKashmir'},
    ]},
    { label: 'area.btn', value: 'Bhutan', children: [
      {value: '', label: 'punakha'},
      {value: '', label: 'bumthang'},
      {value: '', label: 'wangduePhodrang'},
      {value: '', label: 'lhuentse'},
      {value: '', label: 'thimphu'},
      {value: '', label: 'tkashigang'},
      {value: '', label: 'paro'},
      {value: '', label: 'trongsa'},
      {value: '', label: 'ha'},
      {value: '', label: 'monggar'},
      {value: '', label: 'zhemgang'},
      {value: '', label: 'dagana'},
      {value: '', label: 'chhukha'},
      {value: '', label: 'samtse'},
      {value: '', label: 'chirang'},
      {value: '', label: 'pemagatshel'},
      {value: '', label: 'samdrupJongkha'},
      {value: '', label: 'geylegphug'},
    ]},
    { label: 'area.rus', value: 'Russia', children: [
      // {value: '', label: 'taymyrskiyDolganoNenetskiyAvtOkrug'},
      {value: '', label: 'respublikaSakhaYakutiya'},
      {value: '', label: 'evenkiyskiyAvtonomnyyOkrug'},
      {value: '', label: 'yamaloNenetskiyAvtonomnyyOkrug'},
      {value: '', label: 'murmanskayaOblast'},
      {value: '', label: 'respublikaKomi'},
      {value: '', label: 'krasnoyarskiyKray'},
      {value: '', label: 'khantyMansiyskiyAvtonomnyyOkrug'},
      {value: '', label: 'chukotskiyAvtonomnyyOkrug'},
      {value: '', label: 'arkhangelSkayaOblast'},
      {value: '', label: 'respublikaKareliya'},
      {value: '', label: 'irkutskayaOblast'},
      {value: '', label: 'sverdlovskayaOblast'},
      {value: '', label: 'permskayaOblast'},
      {value: '', label: 'vologodskayaOblast'},
      // {value: '', label: 'komiPermyatskiyAvtonOkrug'},
      {value: '', label: 'kirovskayaOblast'},
      {value: '', label: 'tomskayaOblast'},
      {value: '', label: 'magadanskayaOblast'},
      {value: '', label: 'leningradskayaOblast'},
      {value: '', label: 'tyumenskayaOblast'},
      {value: '', label: 'kostromskayaOblast'},
      {value: '', label: 'novgorodskayaOblast'},
      // {value: '', label: 'koryakskiyAvtonomnyyOkrug'},
      {value: '', label: 'pskovskayaOblast'},
      {value: '', label: 'yaroslavskayaOblast'},
      {value: '', label: 'tverskayaOblast'},
      {value: '', label: 'omskayaOblast'},
      {value: '', label: 'udmurtskayaRespublika'},
      // {value: '', label: 'chitinskayaOblast'},
      {value: '', label: 'nizhegorodskayaOblast'},
      {value: '', label: 'ivanovskayaOblast'},
      {value: '', label: 'respublikaMariyEl'},
      {value: '', label: 'novosibirskayaOblast'},
      {value: '', label: 'respublikaBuryatiya'},
      {value: '', label: 'amurskayaOblast'},
      {value: '', label: 'moskovskayaOblast'},
      {value: '', label: 'kurganskayaOblast'},
      {value: '', label: 'kemerovskayaOblast'},
      {value: '', label: 'vladimirskayaOblast'},
      {value: '', label: 'respublikaTatarstan'},
      {value: '', label: 'respublikaBashkortostan'},
      {value: '', label: 'chelyabinskayaOblast'},
      {value: '', label: 'chuvashskayaRespublika'},
      {value: '', label: 'smolenskayaOblast'},
      {value: '', label: 'respublikaKhakasiya'},
      {value: '', label: 'ryazanskayaOblast'},
      {value: '', label: 'kaluzhskayaOblast'},
      {value: '', label: 'respublikaMordoviya'},
      {value: '', label: 'ulYanovskayaOblast'},
      {value: '', label: 'tulSkayaOblast'},
      {value: '', label: 'samarskayaOblast'},
      // {value: '', label: 'kaliningradskayaOblast'},
      {value: '', label: 'khabarovskiyKray'},
      {value: '', label: 'altayskiyKray'},
      {value: '', label: 'orenburgskayaOblast'},
      // {value: '', label: 'ustOrdynskiyBuryatskiyAvtokrug'},
      {value: '', label: 'bryanskayaOblast'},
      {value: '', label: 'penzenskayaOblast'},
      {value: '', label: 'tambovskayaOblast'},
      {value: '', label: 'respublikaTyva'},
      {value: '', label: 'orlovskayaOblast'},
      {value: '', label: 'lipetskayaOblast'},
      {value: '', label: 'saratovskayaOblast'},
      {value: '', label: 'respublikaAltay'},
      {value: '', label: 'kurskayaOblast'},
      {value: '', label: 'voronezhskayaOblast'},
      {value: '', label: 'aginskiyBuryatskiyAvtonomnyyOkrug'},
      {value: '', label: 'belgorodskayaOblast'},
      {value: '', label: 'kamchatskayaOblast'},
      {value: '', label: 'volgogradskayaOblast'},
      {value: '', label: 'rostovskayaOblast'},
      // {value: '', label: 'yevreyskayaAvtonomnayaOblast'},
      // {value: '', label: 'krasnodarskiyKray'},
      {value: '', label: 'stavropolSkiyKray'},
      {value: '', label: 'respublikaAdygeya'},
      {value: '', label: 'kalmykiyaKhalMgTangch'},
      {value: '', label: 'respublikaDagestan'},
      {value: '', label: 'karachayevoCherkesskayaResp'},
      {value: '', label: 'chechenskayaRespublika'},
      {value: '', label: 'kabardinoBalkarskayaResp'},
      {value: '', label: 'respublikaSevernayaOsetiya'},
      {value: '', label: 'ingushskayaRespublika'},
      {value: '', label: 'primorskiyKray'},
      {value: '', label: 'astrakhanskayaOblast'},
      // {value: '', label: 'sakhalinskayaOblast'},
      {value: '', label: 'nenetskiyAvtonomnyyOkrug'},
    ]},
    { label: 'area.kaz', value: 'Kazakhstan', children: [
      {value: '', label: 'soltustikqazaqstan'},
      {value: '', label: 'qostanay'},
      {value: '', label: 'pavlodar'},
      {value: '', label: 'aqmola'},
      {value: '', label: 'batysqazaqstan'},
      {value: '', label: 'shyghysqazaqstan'},
      {value: '', label: 'qaraghandy'},
      {value: '', label: 'aqtobe'},
      {value: '', label: 'qyzylorda'},
      {value: '', label: 'almaty'},
      {value: '', label: 'ongtustik'},
      {value: '', label: 'zhambyl'},
      {value: '', label: 'mangghystau'},
      {value: '', label: 'atyrau'},
    ]},
    { label: 'area.kgz', value: 'Kyrgyzstan', children: [
      {value: '', label: 'chuychu'},
      {value: '', label: 'isykKol'},
      {value: '', label: 'talas'},
      {value: '', label: 'naryn'},
      {value: '', label: 'jalalAbad'},
      {value: '', label: 'osh'},
      {value: '', label: 'biskek'},
    ]},
    { label: 'area.mng', value: 'Mongolia', children: [
      {value: '', label: 'hovsgol'},
      {value: '', label: 'uvs'},
      {value: '', label: 'bulgan'},
      {value: '', label: 'selenge'},
      {value: '', label: 'dornod'},
      {value: '', label: 'dzavhan'},
      {value: '', label: 'darhanuul'},
      {value: '', label: 'hentiy'},
      {value: '', label: 'arhangay'},
      {value: '', label: 'tov'},
      {value: '', label: 'hovd'},
      {value: '', label: 'ulaanbaatar'},
      {value: '', label: 'suhbaatar'},
      {value: '', label: 'govi-altay'},
      {value: '', label: 'ovorhangay'},
      {value: '', label: 'dornogovi'},
      {value: '', label: 'dundgovi'},
      {value: '', label: 'omnogovi'},
      {value: '', label: 'bayanOlgiy'},
      {value: '', label: 'bayanhongor'},
    ]},
    { label: 'area.bgd', value: 'Bangladesh', children: [
      {value: '', label: 'stlhet'},
      {value: '', label: 'dhaka'},
      {value: '', label: 'chittagong'},
      {value: '', label: 'barisal'},
      {value: '', label: 'rajshahi'},
      {value: '', label: 'khulna'},
      {value: '', label: 'rangpur'},
      {value: '', label: 'mymensingh'},
    ]},
    { label: 'area.mmr', value: 'Myanmar', children: [
      {value: '', label: 'kachinState'},
      {value: '', label: 'sagaing'},
      {value: '', label: 'shanState'},
      {value: '', label: 'chinState'},
      {value: '', label: 'mandalay'},
      {value: '', label: 'magway'},
      {value: '', label: 'kayahState'},
      {value: '', label: 'karenState'},
      {value: '', label: 'bago'},
      {value: '', label: 'ayeyarwady'},
      {value: '', label: 'tanintharyi'},
      {value: '', label: 'monState'},
      {value: '', label: 'rakhine'},
      {value: '', label: 'yangon'},
    ]},
    { label: 'area.npl', value: 'Nepal', children: [
      // {value: '', label: 'karnali'},
      // {value: '', label: 'mahakali'},
      {value: '', label: 'seti'},
      // {value: '', label: 'dhalagiri'},
      {value: '', label: 'bheri'},
      // {value: '', label: 'rapti'},
      // {value: '', label: 'gandaki'},
      // {value: '', label: 'bagmati'},
      {value: '', label: 'lumbini'},
      // {value: '', label: 'janakpur'},
      // {value: '', label: 'sagarmatha'},
      {value: '', label: 'koshi'},
      // {value: '', label: 'mechi'},
      {value: '', label: 'narayani'},
    ]},
    { label: 'area.tjk', value: 'Tajikistan', children: [
      {value: '', label: 'khatlon'},
      {value: '', label: 'kuhistoniBadakhshon'},
      {value: '', label: 'regionsofRepublicanSubordination'},
      {value: '', label: 'sughd'},
    ]},
    { label: 'area.tkm', value: 'Turkmenistan', children: [
      {value: '', label: 'dashoguz'},
      {value: '', label: 'lebap'},
      {value: '', label: 'ahal'},
      {value: '', label: 'turkmenistan'},
      {value: '', label: 'balkan'},
    ]},
    { label: 'area.uzb', value: 'Uzbekistan', children: [
      {value: '', label: 'qorqalpoghiston'},
      {value: '', label: 'nawoiy'},
      {value: '', label: 'tashkent'},
      {value: '', label: 'khorazm'},
      {value: '', label: 'namangan'},
      {value: '', label: 'bukhara'},
      {value: '', label: 'jazzakh'},
      {value: '', label: 'andizjon'},
      {value: '', label: 'samarqand'},
      {value: '', label: 'sirdaryo'},
      {value: '', label: 'surkhondaryo'},
      {value: '', label: 'qashqadaryo'},
      {value: '', label: 'fergana'},
    ]},
    { label: 'area.ind', value: 'India', children: [
      {value: '', label: 'jammuKashmir'},
      {value: '', label: 'himachalPradesh'},
      {value: '', label: 'punjab'},
      {value: '', label: 'uttaranchal'},
      {value: '', label: 'haryana'},
      {value: '', label: 'chandigarh'},
      {value: '', label: 'uttarPradesh'},
      {value: '', label: 'rajasthan'},
      {value: '', label: 'delhi'},
      {value: '', label: 'assam'},
      {value: '', label: 'sikkim'},
      {value: '', label: 'bihar'},
      {value: '', label: 'nagaland'},
      {value: '', label: 'madhyaPradesh'},
      {value: '', label: 'meghalaya'},
      {value: '', label: 'manipur'},
      {value: '', label: 'jharkhand'},
      {value: '', label: 'rripura'},
      {value: '', label: 'mizoram'},
      {value: '', label: 'chhattisgarh'},
      {value: '', label: 'damanDiu'},
      {value: '', label: 'kerala'},
      {value: '', label: 'gujarat'},
      {value: '', label: 'goa'},
      {value: '', label: 'karnataka'},
      {value: '', label: 'maharashtra'},
      {value: '', label: 'westBengal'},
      {value: '', label: 'andhraPradesh'},
      {value: '', label: 'telangana'},
      {value: '', label: 'orissa'},
      {value: '', label: 'ramilNadu'},
      {value: '', label: 'lakshadweep'},
      {value: '', label: 'andamanandNicobarIslands'},
      {value: '', label: 'dadraAndNagarHaveli'},
    ]},
  ]